# Makefile for the Himax touchscreen drivers.

# Touch Core Driver Common Header Code..!!
ccflags-y += -I$(srctree)/drivers/input/touchscreen/lge_pos/

obj-$(CONFIG_LGE_TOUCH_HIMAX_HX83112A)   	+= touch_hx83112a.o
obj-$(CONFIG_LGE_TOUCH_HIMAX_HX83112A)   	+= touch_hx83112a_prd.o
